# Generated by Django 5.2.7 on 2025-10-10 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('idBus', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('matrV', models.CharField(max_length=20)),
                ('marque', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matrE', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nomE', models.CharField(max_length=50)),
                ('prenomE', models.CharField(max_length=50)),
                ('dateN', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('telParent', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('refT', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dateTrans', models.DateField()),
                ('idBus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.bus')),
                ('matrE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.etudiant')),
            ],
        ),
    ]
